prioritaires:
  - vous . propriétaire . statut
  - logement . propriétaire occupant
  - logement . résidence principale propriétaire
  - logement . résidence principale locataire
  - ménage . personnes
  - ménage . revenu
  - logement . adresse
  - logement . type
  - logement . surface
  - logement . période de construction
  - logement . commune
  - ménage . commune
  - DPE . actuel
  - parcours d'aide
